# Site settings
title: Timothée Bénédet
description: Timothée Bénédet CV
favicon: /assets/img/avatar.JPG
baseurl: https://ddbullfrog.github.io/resumecard
url: https://ddbullfrog.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Timothée Bénédet
  title: Étudiant alternant en BTS SIO SISR chez IBM Lille
  address: Lille, Haut-de France
  email: timothee.Benedet@mail.com
  link: https://timothee-benedet.github.io/minima/
  weibo:
  github: timothee-benedet
  linkedin: timothee-benedet
  twitter: TimBénédet
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: IBM ISC Lille
      location: Lille, Haut-de-France
      title: Administrateur système AIX/Linux en alternance
      started: 2019
      duration: (2019 - Present)
      description: En tant qu'étudiant en alternance chez IBM ISC Lille, mon but est d'apprendre à administrer des systèmes AIX et Linux pour le compte de différents clients. Pendant mon alternance, j'apprends également à scripter en Bash/Awk et à mettre en place différentes solutions selon les problèmes.
  educationHistory:
    - education3:
      organization: Université Lille III - Charles-de-Gaulle
      location: Villeneuve-d'Ascq, Haut-de-France
      degree: Licence 1 d'Histoire de l'art et Archéologie
      major: Option Monde Médiéval
      started: 2016
      duration: (2016 - 2016)
      description: Licence d'Histoire de l'art et Archéologie
   - education2:
      organization: Université Lille III - Charles-de-Gaulle
      location: Villeneuve-d'Ascq, Haut-de-France
      degree: Licence 1 d'Histoire de l'art et Archéologie
      major: Option Égyptologie
      started: 2014
      duration: (2014 - 2015)
      description: Licence d'Histoire de l'art et Archéologie
    - education1:
      organization: Lycée Arthur Rimbaud
      location: Sin-le-Noble, Haut-de-France
      degree: Baccalauréat
      major: Littéraire
      started: 2009
      duration: (2009 - 2014)
      description: Baccalauréat littéraire
  languages:
    - language1:
      name: Français
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: Bash
      percentage: 65%
    - skill2:
      name: Awk
      percentage: 50%
    - skill3:
      name: HTML/CSS
      percentage: 50%
   
